// autogenerated by sql-generate v0.3.0 on Thu Sep 25 2014 17:21:14 GMT-0400 (Eastern Daylight Time)

var sql = require('sql');


/**
 * SQL definition for unittest.albums
 */
exports.albums = sql.define({
    name: 'albums',
    columns: [
		{ name: 'ID' },
		{ name: 'NAME' },
		{ name: 'COLLECTION_ID' },
		{ name: 'MODIFYSTAMP' },
		{ name: 'CREATESTAMP' },
		{ name: 'DESCRIPTION' }
    ]
});


/**
 * SQL definition for unittest.albums_countries
 */
exports.albums_countries = sql.define({
    name: 'albums_countries',
    columns: [
		{ name: 'ALBUM_ID' },
		{ name: 'COUNTRY_ID' }
    ]
});


/**
 * SQL definition for unittest.cataloguenumbers
 */
exports.cataloguenumbers = sql.define({
    name: 'cataloguenumbers',
    columns: [
		{ name: 'ID' },
		{ name: 'CATALOGUEVALUE' },
		{ name: 'NUMBER' },
		{ name: 'STAMP_ID' },
		{ name: 'CAT_CONDITION' },
		{ name: 'ACTIVE' },
		{ name: 'CATALOGUE_REF' },
		{ name: 'CREATESTAMP' },
		{ name: 'MODIFYSTAMP' },
		{ name: 'UNKNOWN_VALUE' },
		{ name: 'NOTAVAILABLE' }
    ]
});


/**
 * SQL definition for unittest.catalogues
 */
exports.catalogues = sql.define({
    name: 'catalogues',
    columns: [
		{ name: 'ID' },
		{ name: 'NAME' },
		{ name: 'DESCRIPTION' },
		{ name: 'CREATESTAMP' },
		{ name: 'MODIFYSTAMP' },
		{ name: 'ISSUE' },
		{ name: 'TYPE' },
		{ name: 'CURRENCY' }
    ]
});


/**
 * SQL definition for unittest.categories
 */
exports.categories = sql.define({
    name: 'categories',
    columns: [
		{ name: 'ID' },
		{ name: 'NAME' },
		{ name: 'MODIFYSTAMP' },
		{ name: 'CREATESTAMP' },
		{ name: 'DESCRIPTION' }
    ]
});


/**
 * SQL definition for unittest.countries
 */
var countries = sql.define({
    name: 'countries',
    columns: [
		{ name: 'ID' },
		{ name: 'NAME' },
		{ name: 'CATEGORY_ID' },
		{ name: 'MODIFYSTAMP' },
		{ name: 'CREATESTAMP' },
		{ name: 'DESCRIPTION' }
    ]
});
countries.fields =[
    {field: 'name', name: 'NAME', type: 'string', required: true},
    {field: 'desc', name: 'DESCRIPTION', type: 'string'},
    {field: 'id', name: 'ID', type: 'long', required: true},
    {field: 'categoryRef', name: 'CATEGORY_ID', type: 'long', internal: true},
    {field: 'createTimestamp', name: 'CREATESTAMP', type: 'date', internal: true},
    {field: 'modifyTimestamp', name: 'MODIFYSTAMP', type: 'date', internal: true}
    ];

exports.countries = countries;

/**
 * SQL definition for unittest.ownership
 */
exports.ownership = sql.define({
    name: 'ownership',
    columns: [
		{ name: 'ID' },
		{ name: 'CREATESTAMP' },
		{ name: 'MODIFYSTAMP' },
		{ name: 'PRICE' },
		{ name: 'PURCHASED' },
		{ name: 'GRADE' },
		{ name: 'THECONDITION' },
		{ name: 'IMAGE' },
		{ name: 'NOTES' },
		{ name: 'CURRENCY' },
		{ name: 'STAMP_ID' },
		{ name: 'ALBUM_ID' },
		{ name: 'DEFECTS' },
		{ name: 'CERTIFIED' },
		{ name: 'CERTIFIED_IMAGE' },
		{ name: 'DECEPTION' },
		{ name: 'SELLER_ID' }
    ]
});


/**
 * SQL definition for unittest.preferences
 */
exports.preferences = sql.define({
    name: 'preferences',
    columns: [
		{ name: 'ID' },
		{ name: 'CREATESTAMP' },
		{ name: 'CATEGORY' },
		{ name: 'NAME' },
		{ name: 'VALUE' },
		{ name: 'MODIFYSTAMP' }
    ]
});


/**
 * SQL definition for unittest.sellers
 */
exports.sellers = sql.define({
    name: 'sellers',
    columns: [
		{ name: 'ID' },
		{ name: 'CREATESTAMP' },
		{ name: 'DESCRIPTION' },
		{ name: 'MODIFYSTAMP' },
		{ name: 'NAME' }
    ]
});


/**
 * SQL definition for unittest.sequence_gen
 */
exports.sequence_gen = sql.define({
    name: 'sequence_gen',
    columns: [
		{ name: 'ID_NAME' },
		{ name: 'ID_VAL' }
    ]
});


/**
 * SQL definition for unittest.stampcollections
 */
exports.stampcollections = sql.define({
    name: 'stampcollections',
    columns: [
		{ name: 'ID' },
		{ name: 'NAME' },
		{ name: 'DESCRIPTION' },
		{ name: 'MODIFYSTAMP' },
		{ name: 'CREATESTAMP' }
    ]
});


/**
 * SQL definition for unittest.stamps
 */
exports.stamps = sql.define({
    name: 'stamps',
    columns: [
		{ name: 'ID' },
		{ name: 'DESCRIPTION' },
		{ name: 'COUNTRY_ID' },
		{ name: 'DENOMINATION' },
		{ name: 'PRINTING' },
		{ name: 'MODIFYSTAMP' },
		{ name: 'CREATESTAMP' },
		{ name: 'CATALOGUE_COUNT' },
		{ name: 'WANTLIST' }
    ]
});


